---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cycloid/approval-resource
    tag: dev

inputs:
- name: resource-src

run:
  path: resource-src/test/

params:
  AWS_ACCESS_KEY:           ""
  AWS_SECRET_KEY:           ""