#!/bin/bash

set -eux -o pipefail

docker_dir="$( cd "$( dirname "$0" )" && pwd )"
release_dir="$( cd "${docker_dir}" && cd .. && pwd )"
workspace_dir="$( cd "${release_dir}" && cd .. && pwd )"

source "${release_dir}/.envrc"

# outputs
output_dir="${workspace_dir}/build-artifacts"

cp  "${release_dir}/requirements.txt" "${output_dir}/"
cp  -r "${release_dir}/assets" "${output_dir}/"

cp "${docker_dir}/Dockerfile" "${output_dir}/"
